[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "535ydHRcLpUpsCqzHCs3Eg8DFWYKJpsk3qAVh9WqTf8n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/nico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
